# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: SSH into server
        run: ssh -o "StrictHostKeyChecking=no" zahra@67.207.86.11

      - name: clone repo
        run: git clone git@github.com:zahradeenie/devops-practice.git
      
      - name: cd into repo
        run: cd devops-practice
      
      - name: install dependencies
        run: npm install

      - name: run the express server
        run: node index.js
